# Generated by Django 4.2.7 on 2023-11-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QueueCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate", models.CharField(max_length=15, verbose_name="plate")),
                ("position", models.SmallIntegerField(verbose_name="position")),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="is_active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[("A", "Tire_change"), ("V", "Wheelwork")],
                        default="A",
                        max_length=1,
                        verbose_name="service",
                    ),
                ),
            ],
        ),
    ]
