# Generated by Django 4.2.7 on 2023-12-06 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("online_queue", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queuecar",
            name="position",
        ),
    ]
