# Generated by Django 4.2.7 on 2023-12-10 22:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("online_queue", "0003_queuecar_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="queuecar",
            options={"verbose_name": "Queue", "verbose_name_plural": "Queue"},
        ),
    ]
